"""New Migration 4

Revision ID: a31862b6599e
Revises: 343f393226b5
Create Date: 2022-10-10 17:47:42.776047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a31862b6599e'
down_revision = '343f393226b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('package', 'recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
