"""New Migration

Revision ID: b2c0eceb2fb0
Revises: f4a37ad5aeb7
Create Date: 2022-10-10 17:41:08.382334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c0eceb2fb0'
down_revision = 'f4a37ad5aeb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
