"""New Migration 5

Revision ID: f38737d4927d
Revises: a31862b6599e
Create Date: 2022-10-10 17:58:42.886738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38737d4927d'
down_revision = 'a31862b6599e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
